					<div id="contentBackground" class="floatLeft">
						<div id="contentContainer" class="floatLeft">
							<div id="columnleft" class="floatLeft">
								<$sectionmenu cssClass="subNav" showRootMenuItems="false" /$>
								<$region name="LeftContent"$><$/region$>
							</div>
							<div id="columnright" class="floatRight">
								<$region name="MainContent"$><$/region$>
							</div>
						</div>
					</div>