					<div id="footer">
					<$region name="FooterContent"$>
						<ul class="social">
							<li><a href="http://twitter.com/#!/PosttheaterUIT" target="external_link" title="ga naar Twitter">Twitter</a></li>
							<li>|</li>
							<li><a href="http://www.facebook.com/home.php#!/pages/Posttheater/129863003717895" target="external_link" title="ga naar Facebook">Facebook</a></li>
							<li>|</li>
							<li><a href="http://posttheater-arnhem.hyves.nl/" target="external_link" title="ga naar Hyves">Hyves</a></li>
							<li>|</li>
							<li><a href="/sitemap">Sitemap</a></li>
						</ul>
					<$/region$>
						<p class="copyright">Copyright <$date format="yyyy" /$> <$websitename/$>. All Rights Reserved.</p>
					</div><!-- end footer -->
				</div>
			</div>
		</div>