<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="nl" lang="nl">
	<head>
		<title><$websitename/$> | <$pagetitle/$></title>
		<!-- Meta Tags -->
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="imagetoolbar" content="no" />
		<meta name="title" content=" <$pagetitle/$> " />
		<meta name="copyright" content="Copyright (c) <$date format='yyyy' /$>  <$websitename/$>." />
		<meta name="author" content="Publiceervoormij.nl" />
		<meta name="web-author" content="Publiceervoormij.nl" />
		<meta name="web-design" content="www.vandenakkerontwerp.nl" />
		<meta name="Robots" content="index,follow" />
		<link href="css/style.css" rel="stylesheet" type="text/css">
		<link href="css/formvalidate.css" rel="stylesheet" type="text/css">
		<script src="js/jquery-1.5.2.min.js" type="text/javascript"></script>
		<script src="js/json2.js" type="text/javascript"></script>
		<script src="js/jquery.cookie.js" type="text/javascript"></script>
		<script src="js/jlinq.js" type="text/javascript"></script>
		<script src="js/pure.js" type="text/javascript"></script>
		<script src="js/general.js" type="text/javascript"></script>
		<script src="js/validation.js" type="text/javascript"></script>
		<script src="data/productions.js" type="text/javascript"></script>
	</head>​
